### ISSUE TITLE
[ROM][UNOFFICIAL][10.0] LineageOS 17.1 [SM-J530F][NOT TRIED]

### ISSUE THREAD

**Issue by Ammar-Mamo** [rbnyellow/android_device_samsung_j5y17lte#2]
i installed TWRP and Flashed LineageOS 17.1 but when it shoulds to boot ...
it goes in download mode , i rebooted the device but still same
my android version is 9.0 pie (the official one)
TWRP VERSION: 3.3.1 and i can't install any update because it will cause bootloop

**Comment by rbnyellow** [comment]
> i installed TWRP and Flashed LineageOS 17.1 but when it shoulds to boot ...
> it goes in download mode , i rebooted the device but still same
> my android version is 9.0 pie (the official one)
> TWRP VERSION: 3.3.1 and i can't install any update because it will cause bootloop

Not working for now, you can use Maru 0.6, it is working.
